name: lm-training-demo
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python==3.7
  - numpy==1.19.5
  - pip==21.1.2
  - pytorch==1.9.0
  - tqdm==4.41.0
  - pip:
    - pytorch-lightning==1.3.2
    - tokenizers==0.10.2
    - transformers==4.6.0
    - datasets==1.12.1
    - overrides==6.1.0